# /helm/farmAiAssist/values.yaml
replicaCount: 1

image:
  repository: ghcr.io/navneetbca/farm-ai-assist
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

# Only required config now
config:
  SPRING_PROFILES_ACTIVE: k8s

qdrant:
  host: qdrant
  port: "6334"
  collectionName: navneet